# Omakase Ruby styling for Rails
inherit_gem:
  rubocop-rails-omakase: rubocop.yml

# Load the RSpec plugin
plugins:
  - rubocop-rspec


# Overwrite or add rules to create your own house style
AllCops:
  # The version of Ruby that RuboCop will target.
  TargetRubyVersion: 3.4
  # Enable new cops by default
  NewCops: enable
  Exclude:
    - 'deploy-worktree/**/*'

# RSpec rules
RSpec:
  Enabled: true

# Enforce shorthand hash syntax
Style/HashSyntax:
  EnforcedShorthandSyntax: always

RSpec/MultipleExpectations:
  Max: 2
  Exclude:
    - 'spec/system/**/*'
    - 'spec/requests/dev_testing_spec.rb'
    - 'spec/services/dev_playtest/**/*'

RSpec/ExampleLength:
  Exclude:
    - 'spec/system/**/*'
    - 'spec/requests/dev_testing_spec.rb'
    - 'spec/services/dev_playtest/**/*'
