test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

r2:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:r2, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:r2, :secret_access_key) %>
  region: auto
  bucket: <%= "roomrally-uploads-#{Rails.env == 'production' ? 'prod' : 'dev'}" %>
  endpoint: <%= "https://#{Rails.application.credentials.dig(:r2, :account_id)}.r2.cloudflarestorage.com" %>
  force_path_style: true
